services:
  database:
    image: postgres:15.1
    env_file: ./.env
    ports:
      - $POSTGRES_HOST_PORT:$POSTGRES_CONTAINER_PORT
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
#    healthcheck:
#      test: ["CMD-SHELL", "pg_isready -U user"]
#      interval: 10s
#      timeout: 5s
#      retries: 5
  app:
    depends_on:
      - database
    image: rick-morty-app
    build: .
    env_file: ./.env
    ports:
      - $SPRING_HOST_PORT:$SPRING_CONTAINER_PORT
      - $DEBUG_PORT:$DEBUG_PORT
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url" : "jdbc:postgresql://postgres:$POSTGRES_CONTAINER_PORT/$POSTGRES_DB",
        "spring.datasource.username" : "$POSTGRES_USER",
        "spring.datasource.password" : "$POSTGRES_PASSWORD"
      }'
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
